# Dropout Risk Classification

## Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohankrishnathalla/student-academic-performance-and-dropout-risk")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-academic-performance-and-dropout-risk' dataset.
Path to dataset files: /kaggle/input/student-academic-performance-and-dropout-risk

In [3]:
import os
df = pd.read_csv(os.path.join(path, 'student_dropout_risk_2026.csv'))

In [4]:
df.head()

,person_id,age,gender,nationality,first_generation,disability_status,family_income_level,scholarship_holder,tuition_up_to_date,part_time_job,...,library_visits_per_month,lms_logins_per_week,extracurricular_activities,missed_deadlines,stress_level,mental_health_support,satisfaction_score,commute_time_mins,sleep_hours,dropout
0,1,23,Male,Brazil,0,0,Low,1,0,1,...,4,16.3,0,3,8,0,6,37,5.7,0
1,2,18,Other,USA,1,1,High,1,1,0,...,3,8.4,1,1,7,0,6,15,5.4,1
2,3,24,Other,USA,0,0,High,0,1,1,...,3,11.3,1,0,2,0,3,4,4.3,0
3,4,25,Female,USA,0,1,Middle,1,1,0,...,2,13.2,1,1,5,0,7,10,6.7,0
4,5,15,Female,Canada,0,0,Low,1,1,0,...,4,7.4,1,0,7,0,10,24,5.8,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 34 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   person_id                     100000 non-null  int64
 1   age                           100000 non-null  int64
 2   gender                        100000 non-null  object
 3   nationality                   100000 non-null  object
 4   first_generation              100000 non-null  int64
 5   disability_status             100000 non-null  int64
 6   family_income_level           100000 non-null  object
 7   scholarship_holder            100000 non-null  int64
 8   tuition_up_to_date            100000 non-null  int64
 9   part_time_job                 100000 non-null  int64
 10  weekly_work_hours             100000 non-null  int64
 11  course_type                   100000 non-null  object
 12  study_mode                    100000 non-null  object
 13  semester                      100000 non-null  int64
 14  international_student         100000 non-null  int64
 15  admission_grade               100000 non-null  float64
 16  previous_qualification_grade  100000 non-null  float64
 17  units_enrolled                100000 non-null  int64
 18  units_passed                  100000 non-null  int64
 19  units_failed                  100000 non-null  int64
 20  gpa_semester_1                100000 non-null  float64
 21  gpa_semester_2                100000 non-null  float64
 22  attendance_rate               100000 non-null  float64
 23  assignments_submitted_rate    100000 non-null  float64
 24  library_visits_per_month      100000 non-null  int64
 25  lms_logins_per_week           100000 non-null  float64
 26  extracurricular_activities    100000 non-null  int64
 27  missed_deadlines              100000 non-null  int64
 28  stress_level                  100000 non-null  int64
 29  mental_health_support         100000 non-null  int64
 30  satisfaction_score            100000 non-null  int64
 31  commute_time_mins             100000 non-null  int64
 32  sleep_hours                   100000 non-null  float64
 33  dropout                       100000 non-null  int64
dtypes: float64(8), int64(21), object(5)
memory usage: 25.9+ MB

In [6]:
df.describe()

,person_id,age,first_generation,disability_status,scholarship_holder,tuition_up_to_date,part_time_job,weekly_work_hours,semester,international_student,...,library_visits_per_month,lms_logins_per_week,extracurricular_activities,missed_deadlines,stress_level,mental_health_support,satisfaction_score,commute_time_mins,sleep_hours,dropout
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,21.520840,0.420130,0.208770,0.589700,0.784860,0.481920,8.744620,3.617970,0.18094,...,4.366800,7.272294,0.594790,2.372140,6.448120,0.315560,6.318820,23.261360,6.556512,0.320040
std,28867.657797,3.399468,0.493582,0.406432,0.491891,0.410921,0.499676,10.232842,2.112763,0.38497,...,3.651653,3.936264,0.490935,2.587122,2.154185,0.464741,2.079066,23.932468,1.204067,0.466494
min,1.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,4.000000,0.000000
25%,25000.750000,19.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.00000,...,2.000000,4.500000,0.000000,0.000000,5.000000,0.000000,5.000000,6.000000,5.700000,0.000000
50%,50000.500000,21.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,3.000000,0.00000,...,3.000000,7.100000,1.000000,2.000000,7.000000,0.000000,6.000000,16.000000,6.500000,0.000000
75%,75000.250000,24.000000,1.000000,0.000000,1.000000,1.000000,1.000000,18.000000,5.000000,0.00000,...,6.000000,9.800000,1.000000,3.000000,8.000000,1.000000,8.000000,33.000000,7.400000,1.000000
max,100000.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,40.000000,8.000000,1.00000,...,30.000000,29.600000,1.000000,20.000000,10.000000,1.000000,10.000000,120.000000,10.000000,1.000000

In [7]:
df.isna().sum()

person_id                       0
age                             0
gender                          0
nationality                     0
first_generation                0
disability_status               0
family_income_level             0
scholarship_holder              0
tuition_up_to_date              0
part_time_job                   0
weekly_work_hours               0
course_type                     0
study_mode                      0
semester                        0
international_student           0
admission_grade                 0
previous_qualification_grade    0
units_enrolled                  0
units_passed                    0
units_failed                    0
gpa_semester_1                  0
gpa_semester_2                  0
attendance_rate                 0
assignments_submitted_rate      0
library_visits_per_month        0
lms_logins_per_week             0
extracurricular_activities      0
missed_deadlines                0
stress_level                    0
mental_health_support           0
satisfaction_score              0
commute_time_mins               0
sleep_hours                     0
dropout                         0
dtype: int64